version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: 024848481979.dkr.ecr.us-east-1.amazonaws.com/test:latest
    ports:
      - "3000:80"
    depends_on:
      - db

volumes:
  db_data:
