name: Update Docker Compose

on:
  push:
    branches:
      - main

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch helpers/docker-compose branch
        run: |
          git fetch origin helpers/docker-compose
          git fetch origin main

      - name: Checkout and update docker-compose.yml
        run: |
          git checkout helpers/docker-compose -- docker-compose.yml

      - name: Commit and push docker-compose.yml update
        run: |
          git add docker-compose.yml
          git commit -m "Update docker-compose.yml from helpers/docker-compose branch"
          git push origin main
